export const constant = {
  // apiUrl:"http://localhost:3000",
  apiUrl: "https://emb-medx.vercel.app/",
  currency: "AED",
  currencySymbol: "₹",
  errImage:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/2560px-Placeholder_view_vector.svg.png",
  intakeList: [
    { name: "Fat" },
    { name: "Protein" },
    { name: "Carbs" },
    { name: "Calories" },
  ],
  diseases: [
    {
      name: "Facial Skin Care",
      image: "facial.svg",
      keyword: "facial",
    },
    {
      name: "Hair Care",
      image: "dye_1271494.svg",
      keyword: "hair",
    },
    {
      name: "Make Up",
      image: "makeup.svg",
      keyword: "makeup",
    },
    {
      name: "Sun Care",
      image: "oral.png",
      keyword: "sun",
    },
    {
      name: "Treatments",
      image: "eye.png",
      keyword: "eye",
    },
    {
      name: "Beauty offers",
      image: "face-mask.svg",
      keyword: "beauty",
    },
  ],
  nutrition: [
    {
      name: "Protein Supplements",
      image: "nutrition0.png",
      keyword: "nutrition0",
    },
    {
      name: "Energy Bars",
      image: "nutrition1.png",
      keyword: "nutrition1",
    },
    {
      name: "Energy Drinks",
      image: "nutrition2.png",
      keyword: "nutrition2",
    },
    {
      name: "Creatine",
      image: "nutrition3.png",
      keyword: "nutrition3",
    },
    {
      name: "Vitamins and Minerals",
      image: "nutrition4.png",
      keyword: "nutrition4",
    },
    {
      name: "Hydration",
      image: "nutrition5.png",
      keyword: "nutrition5",
    },
  ],
  experience: ["Fresher", "Less than 2 years", "More than 2 years"],
  designation: [
    "Pharmacist (DHA, MOH, DOH License)",
    "Trainee Pharmacist",
    "Consultant Nutritionist",
    "HR Associate",
    "Drivers (Bike or Four Wheelers)",
    "Supporting Staff",
    "Executive (Digital Business & IT)",
    "Executive (Accounts & Finance)",
    "Sales & Marketing Executive",
    "Training Manager",
    "Internal Auditors",
    "CRM Executive",
    "Call Center Associate",
    "MEP Technician",
    "Managers (Retail, HR, IT, Finance & Accounts, CRM, Operations, Procurement)",
  ],
  filters: {
    price: null,
    rating: null,
  },
  cities: [
    "Abu Dhabi",
    "Dubai",
    "Al Ain",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Umm Al Quwain",
    "Fujairah",
  ],
  // designation: ["Trainee Pharmacist",],
  // designation: ["Pharmacist (DHA, MOH, DOH License)",],
  // designation: ["Pharmacist (DHA, MOH, DOH License)",],

  currencies: ["AED", "SAR", "QAR", "KWD", "OMR", "BHD"],

  states: [
    "Dubai",
    "Abu Dhabi",
    "Ajman",
    "Al Alin",
    "Fujairah",
    "Ras Al Khima",
    "Sharjah",
    "Umm Al Quwain",
  ],
};

export const allCountries = [
  {
    name: "United Arab Emirates",
    code: "+971",
    icon: "AE",
    curr: "AED",
  },
  { name: "Saudi Arabia", code: "+966", icon: "SA", curr: "SAR" },
  { name: "Qatar", code: "+974", icon: "QA", curr: "QAR" },
  { name: "Oman", code: "+968", icon: "OM", curr: "OMR" },
  { name: "Bahrain", code: "+973", icon: "BH", curr: "BHD" },
  { name: "Kuwait", code: "+965", icon: "KW", curr: "KWD" },
  { name: "India", code: "+91", icon: "IN", curr: "INR" },
  { name: "United Kingdom", code: "+44", icon: "GB", curr: "GBP" },
  { name: "United States", code: "+1", icon: "US", curr: "USD" },
  { name: "Bhutan", code: "+975", icon: "BT", curr: "BTN" },
  { name: "Afghanistan", code: "+93", icon: "AF", curr: "AFN" },
  { name: "Argentina", code: "+54", icon: "AR", curr: "ARS" },
  { name: "Australia", code: "+61", icon: "AU", curr: "AUD" },
  { name: "Bangladesh", code: "+880", icon: "BD", curr: "BDT" },
  { name: "Belgium", code: "+32", icon: "BE", curr: "EUR" },
  { name: "Brazil", code: "+55", icon: "BR", curr: "BRL" },
  { name: "CANADA", code: "+1", icon: "CA", curr: "CAD" },
  { name: "China", code: "+86", icon: "CN", curr: "CNY" },
  { name: "Colombia", code: "+57", icon: "CO", curr: "COP" },
  { name: "Dominica", code: "+1767", icon: "DM", curr: "XCD" },
  { name: "Chile", code: "+56", icon: "CL", curr: "CLP" },
  { name: "Denmark", code: "+45", icon: "DK", curr: "DKK" },
  { name: "Egypt", code: "+20", icon: "EG", curr: "EGP" },
  { name: "Finland", code: "+358", icon: "FI", curr: "EUR" },
  { name: "France", code: "+33", icon: "FR", curr: "EUR" },
  { name: "Germany", code: "+49", icon: "DE", curr: "EUR" },
  { name: "Hong Kong", code: "+852", icon: "HK", curr: "HKD" },
  { name: "Indonesia", code: "+62", icon: "ID", curr: "IDR" },
  { name: "Iraq", code: "+964", icon: "IQ", curr: "IQD" },
  { name: "Italy", code: "+39", icon: "IT", curr: "EUR" },
  { name: "Belgium", code: "+32", icon: "BE", curr: "EUR" },
  { name: "Japan", code: "+81", icon: "JP", curr: "JPY" },
  { name: "Jamica", code: "+1876", icon: "JM", curr: "JMD" },
  { name: "Kenya", code: "+254", icon: "KE", curr: "KES" },
  { name: "Malaysia", code: "+960", icon: "MY", curr: "MYR" },
  { name: "Maldives", code: "+960", icon: "MV", curr: "MVR" },
  { name: "Mauritius", code: "+230", icon: "MU", curr: "MUR" },
  { name: "Myanmar", code: "+95", icon: "MM", curr: "MMK" },
  { name: "New Zealand", code: "+64", icon: "NZ", curr: "NZD" },
  { name: "Nepal", code: "+977", icon: "NP", curr: "NPR" },
  { name: "Netherlands", code: "+31", icon: "NL", curr: "EUR" },
  { name: "Nigeria", code: "+234", icon: "NG", curr: "NGN" },
  { name: "Norway", code: "+47", icon: "NO", curr: "NOR" },
  { name: "Pakistan", code: "+92", icon: "PK", curr: "PKR" },
  { name: "Poland", code: "+48", icon: "PL", curr: "PLN" },
  { name: "Portugal", code: "+351", icon: "PT", curr: "EUR" },
  { name: "Russia", code: "+7", icon: "RU", curr: "RUB" },
  { name: "Singapore", code: "+65", icon: "SG", curr: "BND" },
  { name: "Souht Africa", code: "+27", icon: "ZA", curr: "ZAR" },
  { name: "Spain", code: "+34", icon: "ES", curr: "EUR" },
  { name: "Sri Lanka", code: "+94", icon: "LK", curr: "LKR" },
  { name: "Switzerland", code: "+41", icon: "CH", curr: "CHF" },
  { name: "Taiwan", code: "+886", icon: "TW", curr: "TWD" },
  { name: "Thailand", code: "+66", icon: "TH", curr: "THB" },
  { name: "Turkey", code: "+90", icon: "TR", curr: "TRY" },
  { name: "Ukraine", code: "+380", icon: "UA", curr: "UAH" },
  { name: "Vietnam", code: "+84", icon: "VN", curr: "VND" },
];

export function getCountryByCode(countryCode) {
  const country = allCountries.find((c) => c.code === countryCode);
  return country || null; // return null if the country code is not found
}

export function getCountryByName(countryName) {
  const country = allCountries.find((c) => c.name === countryName);
  return country || null; // return null if the country code is not found
}